import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { RingCue, RING_CUE_MS, SCREEN_EXIT_CUE_MS } from './ring-cue'

describe('shared ring action choreography', () => {
  beforeEach(() => vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout', 'performance'] }))
  afterEach(() => vi.useRealTimers())
  it('holds a screen-leaving action for its own longer cue and still skips it for reduced motion', () => {
    const leave = vi.fn(), reduced = vi.fn(), cue = new RingCue()
    expect(cue.choose(leave, false, SCREEN_EXIT_CUE_MS)).toBe(true)
    vi.advanceTimersByTime(SCREEN_EXIT_CUE_MS - 1)
    expect(leave).not.toHaveBeenCalled()
    vi.advanceTimersByTime(1)
    expect(leave).toHaveBeenCalledOnce()
    expect(new RingCue().choose(reduced, true, SCREEN_EXIT_CUE_MS)).toBe(true)
    vi.advanceTimersByTime(0)
    expect(reduced).toHaveBeenCalledOnce()
  })
  it('commits only the first answer after its native pulse cue', () => {
    const first = vi.fn(), second = vi.fn(), cue = new RingCue()
    expect(cue.choose(first, false)).toBe(true)
    expect(cue.choose(second, false)).toBe(false)
    vi.advanceTimersByTime(RING_CUE_MS - 1)
    expect(first).not.toHaveBeenCalled()
    vi.advanceTimersByTime(1)
    expect(first).toHaveBeenCalledTimes(1)
    expect(second).not.toHaveBeenCalled()
    expect(cue.choose(second, false)).toBe(false)
  })
  it('Back cancels the pending answer and cannot commit it later', () => {
    const answer = vi.fn(), back = vi.fn(), cue = new RingCue()
    cue.choose(answer, false)
    vi.advanceTimersByTime(100)
    expect(cue.navigate(back)).toBe(true)
    vi.runAllTimers()
    expect(answer).not.toHaveBeenCalled()
    expect(back).toHaveBeenCalledTimes(1)
  })
  it('pauses an accepted answer, rejects input, then resumes the remaining cue', () => {
    const answer = vi.fn(), cue = new RingCue()
    cue.choose(answer, false)
    vi.advanceTimersByTime(100)
    cue.setPlaying(false)
    expect(cue.navigate(vi.fn())).toBe(false)
    vi.advanceTimersByTime(5000)
    expect(answer).not.toHaveBeenCalled()
    cue.setPlaying(true)
    vi.advanceTimersByTime(RING_CUE_MS - 101)
    expect(answer).not.toHaveBeenCalled()
    vi.advanceTimersByTime(1)
    expect(answer).toHaveBeenCalledTimes(1)
  })
  it('unmount cancels pending callbacks', () => {
    const answer = vi.fn(), cue = new RingCue()
    cue.choose(answer, false)
    cue.dispose()
    vi.runAllTimers()
    expect(answer).not.toHaveBeenCalled()
  })
  it('reduced motion eliminates the visual wait while preserving the single commit', () => {
    const answer = vi.fn(), cue = new RingCue()
    cue.choose(answer, true)
    vi.advanceTimersByTime(0)
    expect(answer).toHaveBeenCalledTimes(1)
  })
})
